# Need to use the OOB-mgmt network for acces from the Ansible server
#
- name: add facts from OpenStack discovery
  set_fact:
    ansible_ssh_host: "{{ hostvars[inventory_hostname].openstack.addresses['OOB-mgmt'][0].addr }}"
    
- name: Display all variables/facts known for a host
  debug: var=hostvars[inventory_hostname] verbosity=4

- name: Wait for port 22 to become open
  local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10 timeout=1200

- name: touch a file
  command: touch /tmp/iwashere.txt
